version: '3.8'
name: tenancy-example-dev

x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - tenancy_example_network

networks:
  tenancy_example_network:
    external: true

volumes:
  tenancy_example_db_data:
    external: true

services:

  ####################################################################  

  db:
    <<: *defaults
    image: postgres:15.3-alpine3.17
    ports:
      - '5432:5432'
    volumes:
      - tenancy_example_db_data:/var/lib/postgresql/data
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 07f019e661d8ca48c47bdffd255b12fe

  ####################################################################           

  proxy:
    <<: *defaults
    image: nginx:1.23.4-alpine3.17
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  ####################################################################

  frontend:
    <<: *defaults
    depends_on:
      - backend
    expose:
      - 3000
    command: yarn workspace frontend dev
    environment:
      - PORT=3000
    build:
      args:
        APP: frontend
        START_COMMAND: dev
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/apps/frontend/.next

  ####################################################################

  backend:
    <<: *defaults
    expose:
      - 3333
    command: yarn workspace backend start:dev
    environment:
      - PORT=3333
      - IN_CONTAINER=1
    build:
      args:
        APP: backend
        START_COMMAND: start:dev
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/node_modules
      - /app/apps/backend/node_modules
  ####################################################################    
